### PR TITLE
Use clink_release to build

### PR DESCRIPTION
**Pull request by KayLeung**

### CODE REVIEW

**Comment by Stanzilla** [comment]
I think appveyor is missing the xp toolkit

**Comment by Stanzilla** [comment]
fun fact: ? is not an allowed name for folders, so the git check is going wrong and therefore that variable is ?

**Comment by KayLeung** [comment]
It's interesting. I cloned the repo to gitlab and it works.

**Comment by Stanzilla** [comment]
very weird...

**Comment by KayLeung** [comment]
gitlab @see https://ci.appveyor.com/project/KayLeung/clink-l7225/build/artifacts

**Comment by Stanzilla** [comment]
hrm gitlab has a git clone and checkout that the github version does not have

**Comment by Stanzilla** [comment]
Oh god, I think it's shallow_clone.

Edit: yes! GitLab does not support shallow_clone which is why it worked there!

**Comment by Stanzilla** [comment]
With shallow_clone it was not a git checkout at all, which is why all git actions failed, obviously.

**Pull request closed without merging**
